### PR TITLE
Add Icons, Converti and Horizontal swing support

### PR DESCRIPTION
**Pull request by deCodeIt**
Adds the much-awaited Horizontal and Converti support with icons.
_Note: This requires `miraie-ac==1.0.4` to work properly._

### Horizontal Support

- Remove existing Swing levels ON, 1, 2, 3, 4, 5
- Add Vertical swing levels 0(auto), 1, 2, 3, 4, 5
- Add Horizontal swing levels 0(auto), 1, 2, 3, 4, 5

#### Caveat
HomeAssistant does not provide separate functionality to horizontal and vertical swings so they have been clubbed together to function correctly but with reduced observation as follows:

The Vertical states are preferred over horizontal states unless the vertical state is set to V0(auto).
You can take a look at the following table to understand the outcome.
| Mode set in UI | Mode set in AC | Mode displayed on UI when vertical swing is on auto mode | Mode displayed on UI when vertical swing is NOT on auto mode |
|---|---|---|---|
| V0 | V0 | V0 | V0 |
| V1 | V1 | V1 | V1 |
| V2 | V2 | V2 | V2 |
| V3 | V3 | V3 | V3 |
| V4 | V4 | V4 | V4 |
| V5 | V5 | V5 | V5 |
| H0 | H0 | H0 | Vx |
| H1 | H1 | H1 | Vx |
| H2 | H2 | H2 | Vx |
| H3 | H3 | H3 | Vx |
| H4 | H4 | H4 | Vx |
| H5 | H5 | H5 | Vx |

Here `Vx` is the swing mode set before and x can be either of 1, 2, 3, 4, 5.
Note: Even with `Vx` being displayed on the UI the AC would still be set to proper Horizontal swing mode so you can use your automation to control the horizontal swing mode but might not be able to watch for mode changes in horizontal mode.

### Converti mode support

All converti modes are now supported via Presets on UI. The following converti modes have been added:
- cv 110 (High Capacity)
- cv 100 (Full Capacity)
- cv 90
- cv 80
- cv 70
- cv 55
- cv 40
- cv 0 (Off)
Screenshot 2024-07-31 at 3 08 16 PM

### Icons
To assist the end user with setting proper swing levels, icons have been added to both vertical and horizontal swings.
Screenshot 2024-07-31 at 3 08 10 PM

### CODE REVIEW

**Comment by deCodeIt** [comment]
Tagging @rkzofficial to take a look. Do note that this requires `miraie-ac==1.0.4`

**Comment by rkzofficial** [comment]
> Tagging @rkzofficial to take a look. Do note that this requires `miraie-ac==1.0.4`

Yes I have deployed the v1.0.4 to pypi, I will take a look at this in few hours.

**Comment by rkzofficial** [comment]
@deCodeIt Everything looks good, Thanks for the pull request.

Let's merge it then.

**Comment by cogentcoder** [comment]
@rkzofficial I noticed that new release has no hot mode which was visible in previous version. As my Panasonic is hot and cold (Model CS-KZ18ZKYF from 2023), it was very useful. Can you please check if hot can be provided again as in previous release?
Thank you!

**Comment by deCodeIt** [comment]
> @rkzofficial I noticed that new release has no hot mode which was visible in previous version. As my Panasonic is hot and cold (Model CS-KZ18ZKYF from 2023), it was very useful. Can you please check if hot can be provided again as in previous release? Thank you!

@cogentcoder The new release only adds to the existing modes. There was no hot/heat mode support ever in this component before.

Although if you're interested and are open to sharing your miraie credentials (temporarily) so that we can debug your ac to explore the possibilities of adding heat/hot mode support then do let me know [Telegram](https://t.me/+n4Okha-RHAo4OTM1)

**Comment by cogentcoder** [comment]
@deCodeIt Thanks for the reply. Yes sure, I can share miraie login credentials. My telegram username is @nk38492, once you ping me there I'll share the credentials there. 
Thank you.

**Comment by deCodeIt** [comment]
> @deCodeIt Thanks for the reply. Yes sure, I can share miraie login credentials. My telegram username is @nk38492, once you ping me there I'll share the credentials there. Thank you.

@cogentcoder I've raised a couple of PRs which will add log support and you might not need to share credentials anymore if those are merged. Let's wait for them to be added and I'll share further steps so you can share the logs with us. Also, can you raise an issue for this or perhaps tag me in the original issue so we can follow up there instead of on this closed PR?

**Pull request merged**
